### ISSUE TITLE
[工具] 是否要採用 forester 做成網站？

### ISSUE THREAD

**Issue by dannypsnl** [FizzyElt/functional-programming#24]
- 工具本身 https://sr.ht/~jonsterling/forester/
- 介紹 https://www.jonmsterling.com/tfmt-000V.xml

Template: https://git.sr.ht/~jonsterling/forest-template

**Comment by dannypsnl** [comment]
初步實驗，連結效果還不錯，程式的 css 要再調整

<img width="1135" alt="image" src="https://github.com/FizzyElt/functional-programming/assets/22004511/21a56209-899b-4806-b1a9-27bcc6fa01c1">

**Comment by dannypsnl** [comment]
多行程式要排版正確要用下面的寫法

```tree
\pre{\startverb%
function xxx() {
  // ...
}
\stopverb}
```

**Comment by FizzyElt** [comment]
tree 的名稱有限制嗎，可能需要一點命名規則

**Comment by FizzyElt** [comment]
我在想如果用這種形式，我們是否需要保留原始 markdown

**Comment by dannypsnl** [comment]
Tree 的名稱是隨意的

如果都在 tree 上面寫，之後移植完應該就不需要 markdown 了

**Comment by dannypsnl** [comment]
另一個辦法是把 tree 解析成 markdown

應該不複雜，語法比較規範

**Comment by dannypsnl** [comment]
順帶一提 000A 這個是 36 進位，所以一個 namespace 有 1679616 個入口，應該很難用光

**Comment by dannypsnl** [comment]
close as start experiement
