### ISSUE TITLE
[Functor] FP 中的 functor 跟 Category theory 的 functor

### ISSUE THREAD

**Issue by FizzyElt** [FizzyElt/functional-programming#42]
FP 中的 functor 跟 Category theory 的 functor，兩者之間的關係是什麼？

**Comment by dannypsnl** [comment]
一般來說語言裡面定義的 functor 都比較弱，只是 endofunctor 而且是 pointwise  的

**Comment by FizzyElt** [comment]
應該可以對這部份作個簡單說明，避免讀者有錯誤的解讀

**Comment by FizzyElt** [comment]
相關討論
https://github.com/FizzyElt/functional-programming/discussions/63
