### ISSUE TITLE
[Github Action] forester 錯誤

### ISSUE THREAD

**Issue by FizzyElt** [FizzyElt/functional-programming#45]
目前 github action 會報錯，好像是 forester 問題？
https://github.com/FizzyElt/functional-programming/actions/runs/6518133179/job/17714998886

**Comment by dannypsnl** [comment]
嗯我記得要加個目錄，可能可以查看我的blog的新提交

**Comment by FizzyElt** [comment]
我找不到你的 blog Repo 😅

**Comment by dannypsnl** [comment]
https://sr.ht/~dannypsnl/blog/
