### ISSUE TITLE
[category] F-algebra

### ISSUE THREAD

**Issue by dannypsnl** [FizzyElt/functional-programming#75]
翻譯這篇 https://dannypsnl.me/math-001K.xml 到 repo

**Comment by dannypsnl** [comment]
喔！另外一定要談到這就是為什麼 inductive/coindcutive 是 initial algebra

**Comment by dannypsnl** [comment]
啊這個應該可以寫成 algebra of endofunctor $F$ is a morphism $F x \to x$

**Comment by FizzyElt** [comment]
想請教，關於 initial object 跟 terminal object 在這裡起什麼作用，為什麼會需要這兩個東西

**Comment by dannypsnl** [comment]
因為對固定的 F 來說，它全部的代數構成的範疇的 initial 跟自己的原始物件同構

**Comment by FizzyElt** [comment]
我可以翻譯這篇，可能會順便從中提出一些我不太了解的部份當作是一種 Q&A

**Comment by FizzyElt** [comment]
![Screenshot from 2023-11-18 22-27-43](https://github.com/FizzyElt/functional-programming/assets/43887006/c16af8b1-030c-41bb-b14b-f6722cf142b8)
這圖要怎麼畫出來

**Comment by dannypsnl** [comment]
quiver

**Comment by dannypsnl** [comment]
但在 forester 裡面要寫成 `\tex{\begin{tikzcd}\end{tikzcd}}`

**Comment by FizzyElt** [comment]
不知為啥會有 error，在之前的語法裡完全沒問題
![Screenshot from 2023-11-19 01-03-08](https://github.com/FizzyElt/functional-programming/assets/43887006/fbf5b342-151c-4b19-8d70-9f8b1cbfe08d)

**Comment by dannypsnl** [comment]
Texlive 可能要檢查一下吧？我用 Mac 試試看

**Comment by dannypsnl** [comment]
我這邊沒問題，所以應該是 latex 的毛，你可以複製有問題的指令（有印出）然後到 build 目錄裡面測試一下

**Comment by FizzyElt** [comment]
我把 texlive 重裝成 2023 版本還是有會有錯，但目前追蹤到的是執行 pdflatex 這個指令時出問題，不過不知道從何修起 😢 
![Screenshot from 2023-11-19 21-48-23](https://github.com/FizzyElt/functional-programming/assets/43887006/0a69d254-42b6-4609-87d8-4c537002f068)

**Comment by dannypsnl** [comment]
我覺得可以嘗試把 amsthm 直接引用，然後把上面的 ifpdf 條件式去掉之類的，去看在哪裡出錯

**Comment by dannypsnl** [comment]
另外就是你用哪個 texlive，相關資訊應該可以查一下
1. 版本
2. bundle（一起安裝的套件們）

**Comment by FizzyElt** [comment]
我有嘗試把 tikzcd 的內容修改
這樣可以動
```text
\begin{tikzcd}
a
\end{tikzcd}
```

這樣會噴錯```text
\begin{tikzcd}
a
\end{tikzcd}
```

**Comment by dannypsnl** [comment]
太神奇了，可能 `\bullet` 是什麼套件提供的？

**Comment by FizzyElt** [comment]
我懷疑我少裝什麼導致無法解析

**Comment by FizzyElt** [comment]
最新進展，`\bullet`, `\cdot` 兩個都沒辦法用
可能是我字體問題，但我實在沒心力 debug
不過還好目前的圖都用不到 `\bullet`, `\cdot`

**Comment by FizzyElt** [comment]
這是關於 F-algebra 一些提問

一開始所寫的簽名我們該怎麼解讀它
```math
\begin{cases}
1:1\to m \\
\bullet: m \times m \to m
\end{cases}
```

我們怎麼從上方得出這個態射的 $1+m \times m \to m$

**Comment by dannypsnl** [comment]
取簽名裡面所有 `... -> m` 的 `...`

**Comment by dannypsnl** [comment]
群環體對數學背景的人來說應該很具體，要程式的案例的話 inductive types 就是了

**Comment by dannypsnl** [comment]
當然 inductive types 是這些推理的結果，你需要什麼樣的案例？

**Comment by FizzyElt** [comment]
這邊倒是還好，主要是 Catamorphism 那邊的不動點需要一點案例

**Comment by FizzyElt** [comment]
或者我們可以後續用一個 Functor 實作來呼應這邊的內容

**Comment by dannypsnl** [comment]
那你應該可以用 ListAlg 試試看，後面應該是沒必要，因為 catamorphism 不怎麼實用，主要還是一種數學上的關聯

**Comment by dannypsnl** [comment]
案例的話，在 PR 修完之後可以看這篇《Clowns to the Left of me, Jokers to the Right》

**Comment by FizzyElt** [comment]
這篇是文章嘛，還是書

**Comment by dannypsnl** [comment]
論文

**Comment by dannypsnl** [comment]
另一篇有用的論文是

《Containers: Constructingstrictly positive types》
M. Abbott et al. / Theoretical Computer Science 342 (2005) 3 – 27

這個是上面 Clown Joker 講到的 container functors 的細節

**Comment by dannypsnl** [comment]
<img width="1039" alt="image" src="https://github.com/FizzyElt/functional-programming/assets/22004511/cd6e0371-7c0e-419c-bcf7-e5f56617bfc3">

**Comment by FizzyElt** [comment]
Clowns to the Left of me, Jokers to the Right 這篇要去哪裡找

**Comment by dannypsnl** [comment]
http://strictlypositive.org/CJ.pdf
