### ISSUE TITLE
Monoid

### ISSUE THREAD

**Issue by dannypsnl** [FizzyElt/functional-programming#8]
Monoid 是由集合 $S$ 跟下述簽名組成的

$$
\displaylines{
1 : S \\
\otimes : S \times S \to S
}
$$

並滿足相等規則
1. $(a \otimes b) \otimes c = a \otimes (b \otimes c)$
2. $a \otimes 1 = a = 1 \otimes a$

因此 Monoid 恰好是只有一個物件的 locally small category，identity morphism 對應 $1$，而組合兩個 morphism 正好得到另一個 morphism

**Comment by FizzyElt** [comment]
幫我看一下 PR 是否有誤的地方需要修改 🙏🏼
