### ISSUE TITLE
Forester 3.0 有 break changes

### ISSUE THREAD

**Issue by dannypsnl** [FizzyElt/functional-programming#86]

**Comment by dannypsnl** [comment]
I test with the non-latest version still, forgot to upgrade my personal computer's forester......

**Comment by dannypsnl** [comment]
I'm not sure about `theme/` requirement, let me check about it

**Comment by dannypsnl** [comment]
Wait CI passing

**Comment by dannypsnl** [comment]
Fixed, but there is another problem that I will describe in new issue.

**Comment by FizzyElt** [comment]
3.0 的連結在哪裡，我只找到 2.5.1

**Comment by dannypsnl** [comment]
那個就是 3.0: https://www.jonmsterling.com/jms-00CW.xml
