### ISSUE TITLE
[CI/CD] Circle CI 設定

### ISSUE THREAD

**Issue by FizzyElt** [FizzyElt/functional-programming#97]
正在摸熟 Circle CI 中，目前會先嘗試能不能 build 成功

**Comment by dannypsnl** [comment]
因為 action 修好了這個應該可以無限期延後？

**Comment by FizzyElt** [comment]
怎麼修好的

**Comment by dannypsnl** [comment]
安裝 xpatch

**Comment by dannypsnl** [comment]
https://github.com/FizzyElt/functional-programming/commit/7ac5b24f4d3ae6447cbc0f3e5b4445aeee765578
